name: Deploy in Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js app
      run: |
        NEXT_PUBLIC_API_BASE_URL=https://www.cuoco.com.ar/api \
        NEXT_PUBLIC_ENABLE_MSW=true \
        npm run build

    - name: Prepare deployment folder
      run: |
        mkdir -p deploy
        cp -r .next public package*.json deploy/

    - name: Copy build to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DO_SSH_HOST }}
        username: ${{ secrets.DO_SSH_USER }}
        key: ${{ secrets.DO_SSH_KEY }}
        source: "deploy/*"
        target: "/opt/cuoco/prod/frontend"

    - name: Restart frontend on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DO_SSH_HOST }}
        username: ${{ secrets.DO_SSH_USER }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          cd /opt/cuoco/prod/frontend
          docker compose down
          docker compose up -d --build
